### ISSUE TITLE
LBP1120 x CAPT Dissector

### ISSUE THREAD

**Issue by ra1nst0rm3d** [mounaiban/studycapt#1]
I have my LBP1120 connected over USB, but it works through usblp driver. It's parallel printer or USB?

**Comment by mounaiban** [comment]
@ra1nst0rm3d USB. As long as the data goes over USB, usbmon should pick it up. If usbmon can capture it, the CAPT dissector will work (well, most of the time for me anyway :sweat_smile:)

If capturing works but the dissector doesn't dissect, try adding this line to the `dissector registration` section in `capt.lua`:
```lua
dt_usb_product:add(0x04a9262b, capt_proto) -- LBP1120
```
Please be aware that you _will_ get out of bounds errors on some packets because the dissector is catered for CAPT 2.1 and makes naive assumptions on packet sizes.

As far as I know the `lp` in `usblp` is just a historical artifact.

**Comment by ra1nst0rm3d** [comment]
Now it works, thx)

**Comment by mounaiban** [comment]
@ra1nst0rm3d I have updated the dissector to enable LBP1120 support out of the box. Please let me know if it works for you.
